/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.necessarysense.sudoku

import main.kotlin.com.necessarysense.sudoku.Board
import main.kotlin.com.necessarysense.sudoku.ImpossibleBoard

fun main() {
    val puzzle1 = Board.parseGrid("003020600900305001001806400008102900700000008006708200002609500800203009005010300")
    when (puzzle1) {
        is ImpossibleBoard -> println("The board could not be assigned")
        is Board -> puzzle1.display()
    }
}
